# Danilinux 2.2 - login screen look (Vista Aero)
[greeter]
background=/usr/share/backgrounds/danilinux/aero-aurora.jpg
theme-name=Danilinux-Aero
icon-theme-name=elementary-xfce
font-name=Selawik 10
user-background=false
