# Configuration file for Calamares — Danilinux 2.2
# Based on calamares-settings-debian (GPL-2.0+, Copyright Jonathan Carter et al.)
# Syntax is YAML 1.2
---

modules-search: [ local, /usr/lib/calamares/modules ]

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

quit-at-end: false

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - luksbootkeyfile
  - dpkg-unsafe-io
  - sources-media
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config
  - grubcfg
  - bootloader
  - packages
  - plymouthcfg
  - initramfscfg
  - initramfs
  - dpkg-unsafe-io-undo
  - sources-media-unmount
  - danilinux-finalize
  - umount

- show:
  - finished

branding: danilinux

prompt-install: false

dont-chroot: false
